version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    image: "jenkins"
    ports:
      - "49001:8080"
      - "5000:5000"
    volumes:
      - "/disk3/data-jenkins:/var/jenkins_home"