version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    image: "jenkinsci/blueocean"
    ports:
      - "49001:8080"
    volumes:
      - "/disk3/data-jenkins:/var/jenkins_home"